version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "sysadm"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
